[package]
name = "Rust-Async"
version = "0.1.0"
authors = ["Tooba Malaika <toobachuhan92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
async-std = "1"
